version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lisk-across-relayer
hooks:
  ApplicationStop:
    - location: scripts/lisk/docker/composeStop.sh
  ApplicationStart:
    - location: scripts/lisk/docker/composeStart.sh
