version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lisk-across-relayer
hooks:
  AfterInstall:
    - location: scripts/installDependencies.sh
    - location: scripts/installApplication.sh
      runas: root
  ApplicationStart:
    - location: scripts/runMainnet.sh
      runas: root
